kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-volume-3
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv3"
